#!/usr/bin/env bash
# Generated by harness-creator for ${PROJECT_NAME} (stack: ${STACK}).
# Run this before starting work and again before claiming any feature "done" —
# capture the real output as evidence in feature_list.json, don't self-report.
set -euo pipefail

echo "== ${PROJECT_NAME} verification (${STACK}) =="

${VERIFICATION_COMMANDS}

echo ""
echo "== Verification complete =="
echo "Next: review ${STATE_DIR}/feature_list.json, pick one feature with status"
echo "not-started or in-progress, implement it, then rerun this script before"
echo "marking it pass."
